version: '3.8'

services:

  recipes_db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      app_net:
        ipv4_address: 172.16.238.20

  user_db:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      app_net:
        ipv4_address: 172.16.238.30
    
  recipes_db_adapter:
    build:
      context: ./recipes-db-adapter
    ports:
      - "5000:5000"
    networks:
      app_net:
        ipv4_address: 172.16.238.40
  
  user_db_adapter:
    build:
      context: ./user-db-adapter
    ports:
      - "5001:5001"
    networks:
      app_net:
        ipv4_address: 172.16.238.50
  
  food_api:
    build: 
      context: ./food_game_api
    ports: 
      - "30000:30000"
    networks: 
      app_net:
        ipv4_address: 172.16.238.60

  food_frontend:
    build: 
      context: ./food-game-frontend
    ports: 
      - "4200:4200"
    networks: 
      app_net:
        ipv4_address: 172.16.238.70
  
  matchservice:
    build: 
      context: ./matchservice
    ports: 
      - "8080:8080"
    networks: 
      app_net:
        ipv4_address: 172.16.238.80

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"