version: '3.8'

services:

  recipes_db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      app_net:
        ipv4_address: 172.16.238.20

  recipes_db_adapter:
    build:
      context: ./recipes_db_adapter
    ports:
      - "5000:5000"
    networks:
      app_net:
        ipv4_address: 172.16.238.30
 
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"